/**
 * DodoRail's Ika dWallet integration — client factory.
 *
 * Ika (ika.xyz) provides 2PC-MPC threshold signatures via "dWallets" — virtual
 * wallets whose signing authority is split between the user and a Solana
 * program. This lets a Solana smart contract programmatically control native
 * assets on Bitcoin / Ethereum / Zcash / Cardano / Stellar / Near WITHOUT
 * bridges or wrapped tokens.
 *
 * For DodoRail this means a customer can pay a merchant in native BTC or ETH
 * and the merchant receives USDC on Solana. The customer's BTC lands in an
 * Ika-controlled dWallet whose signing authority belongs to the DodoRail
 * Solana program, which releases USDC to the merchant when the BTC is
 * confirmed. Zero bridges. Zero custodians.
 *
 * Architectural-only as of 2026-04-30:
 *   - Ika's Solana integration is PRE-ALPHA (https://docs.ika.xyz/docs/sdk).
 *     Their docs explicitly state: "all signatures are generated by a single
 *     mock signer, not a distributed network. Do not rely on current
 *     security guarantees."
 *   - Persistence: "All on-chain data will be deleted during the transition
 *     to Alpha 1."
 *   - This wrapper exposes the FIVE-STEP workflow Ika documents
 *     (createDWallet → transferAuthority → approveMessage → getSignature →
 *     readMessageApproval) so DodoRail's pay flow can demonstrate the
 *     architecture end-to-end against the mock signer.
 *   - When Ika ships Alpha 1 (timeline TBD per their team), the live mode
 *     here flips to real distributed signatures with no DodoRail-side code
 *     changes — all the protocol-shape work is done.
 *
 * Design choices in this wrapper:
 *   - Same factory contract as @dodorail/cloak / @dodorail/umbra / etc.
 *   - Mock mode ALWAYS works regardless of network — useful since Ika's
 *     pre-alpha endpoint is rate-limited
 *   - Live mode dynamic-imports @ika.xyz/sdk so the bundle stays small for
 *     mock-only consumers (most of DodoRail today)
 *   - Returns receive addresses across 6 supported chains (BTC, ETH, ZEC,
 *     ADA, XLM, NEAR) so customer-facing code can render the right chain UI
 *
 * Research doc: /FRONTIER/15_Frontier-Encrypt-Ika-Track_Master-Research.docx
 */

import type { PublicKey } from "@solana/web3.js";

export type IkaMode = "live" | "mock";
export type IkaNetwork = "solana-pre-alpha" | "solana-mainnet";

/** Chains an Ika dWallet can hold native assets on. */
export type IkaSupportedChain =
  | "bitcoin"
  | "ethereum"
  | "zcash"
  | "cardano"
  | "stellar"
  | "near";

export interface IkaClientOptions {
  /** Network — defaults to solana-pre-alpha (the only operational option as
   * of April 2026). */
  network?: IkaNetwork;
  /** Override the Ika gRPC endpoint. Defaults to solana-pre-alpha.ika.xyz. */
  endpointUrl?: string;
  enabled?: boolean;
  mode?: IkaMode;
}

export interface IkaDWallet {
  /** Unique identifier for this dWallet. */
  dwalletId: string;
  /** Which chain this dWallet holds native assets on. */
  chain: IkaSupportedChain;
  /** The receive address on the target chain — what customers send funds to. */
  receiveAddress: string;
  /** The public key derived from the distributed key generation. */
  publicKey: string;
  /** Solana PDA (program-derived address) that owns the signing authority. */
  authorityPda?: string;
  /** Status of the DKG ceremony. */
  status: "pending_dkg" | "ready" | "authority_transferred";
  createdAt: string;
}

export interface IkaSignatureRequest {
  /** Which dWallet should sign. */
  dwalletId: string;
  /** The bytes the dWallet should produce a signature over. For BTC / ETH
   * this is the transaction hash; for arbitrary messages it's the message
   * bytes. */
  message: Uint8Array;
  /** Reason recorded on-chain in the MessageApproval account. */
  reason: string;
}

export interface IkaSignatureResult {
  signatureId: string;
  /** The 2PC-MPC threshold signature (in pre-alpha, produced by mock signer). */
  signature: string;
  /** Solana account where the MessageApproval is recorded. */
  messageApprovalAccount: string;
  /** Mock-mode flag — true when the signature came from the pre-alpha mock
   * signer rather than a distributed validator set. ALWAYS true today. */
  mockSigner: boolean;
  signedAt: string;
}

export interface IkaClient {
  readonly mode: IkaMode;
  readonly network: IkaNetwork;
  readonly featureFlag: boolean;

  initialise(): Promise<void>;
  healthcheck(): Promise<{ ok: boolean; latencyMs: number; message?: string }>;

  /** Step 1 — Solana program triggers DKG to create a dWallet on the target
   * chain. Returns receive address customers can send funds to. */
  createDWallet(input: {
    chain: IkaSupportedChain;
    invoiceId: string;
  }): Promise<IkaDWallet>;

  /** Step 2 — transfer signing authority from the dWallet creator to a
   * Solana program PDA. After this, only the Solana program (per its own
   * logic) can authorise signatures. */
  transferAuthority(input: {
    dwalletId: string;
    programPdaAddress: string;
  }): Promise<{ ok: boolean; signature: string }>;

  /** Step 3 — Solana program calls approveMessage when its policy is
   * satisfied (e.g. "the BTC has confirmed at the receive address"). Ika's
   * validator set (or the pre-alpha mock signer) produces the threshold
   * signature. */
  approveMessage(input: IkaSignatureRequest): Promise<IkaSignatureResult>;

  /** Step 4 — read the resulting signature client-side from the
   * MessageApproval account so it can be submitted to the target chain. */
  readMessageApproval(input: {
    messageApprovalAccount: string;
  }): Promise<{ signature: string; readyForBroadcast: boolean }>;

  /** Convenience helper — list the supported chains + a per-chain note about
   * what currently works on the pre-alpha. */
  supportedChains(): Array<{
    chain: IkaSupportedChain;
    label: string;
    signatureScheme: "ECDSA" | "EdDSA";
    preAlphaStatus: "supported" | "documented_only";
  }>;
}

const DEFAULT_PRE_ALPHA_ENDPOINT = "https://solana-pre-alpha.ika.xyz";

const SUPPORTED_CHAINS: ReturnType<IkaClient["supportedChains"]> = [
  { chain: "bitcoin", label: "Bitcoin", signatureScheme: "ECDSA", preAlphaStatus: "supported" },
  { chain: "ethereum", label: "Ethereum", signatureScheme: "ECDSA", preAlphaStatus: "supported" },
  { chain: "zcash", label: "Zcash", signatureScheme: "EdDSA", preAlphaStatus: "supported" },
  { chain: "cardano", label: "Cardano", signatureScheme: "EdDSA", preAlphaStatus: "documented_only" },
  { chain: "stellar", label: "Stellar", signatureScheme: "EdDSA", preAlphaStatus: "documented_only" },
  { chain: "near", label: "NEAR", signatureScheme: "EdDSA", preAlphaStatus: "documented_only" },
];

function mockReceiveAddress(chain: IkaSupportedChain, invoiceId: string): string {
  const seed = invoiceId.slice(0, 8);
  switch (chain) {
    case "bitcoin":
      return `bc1qmock${seed}${Math.random().toString(36).slice(2, 30)}`;
    case "ethereum":
      return `0xmock${seed}${Math.random().toString(36).slice(2, 38).padEnd(36, "0")}`;
    case "zcash":
      return `zsmock${seed}${Math.random().toString(36).slice(2, 70)}`;
    case "cardano":
      return `addr1mock${seed}${Math.random().toString(36).slice(2, 50)}`;
    case "stellar":
      return `Gmock${seed}${Math.random().toString(36).slice(2, 50).toUpperCase()}`;
    case "near":
      return `mock${seed}.${chain}.near`;
  }
}

export function createIkaClient(options: IkaClientOptions = {}): IkaClient {
  // Mock is the default because live mode currently means "pre-alpha mock
  // signer" — there's no real distributed signing to opt into yet. We keep
  // the mode flag for future-state (Alpha 1+).
  const mode: IkaMode = options.mode ?? "mock";
  const network: IkaNetwork = options.network ?? "solana-pre-alpha";
  const enabled = options.enabled ?? true;
  const endpointUrl = options.endpointUrl ?? DEFAULT_PRE_ALPHA_ENDPOINT;

  function guard(op: string): void {
    if (!enabled) {
      throw new Error(`[@dodorail/ika] ${op} called while featureFlag is false.`);
    }
    if (mode === "live" && network === "solana-mainnet") {
      throw new Error(
        `[@dodorail/ika] ${op}: solana-mainnet not yet operational. Ika's mainnet timeline is post-Alpha-1 (TBD by their team). Use solana-pre-alpha for now.`,
      );
    }
  }

  async function initialise(): Promise<void> {
    if (mode === "mock") return;
    guard("initialise");
    // Pre-alpha SDK warms up lazily on first dWallet creation. Nothing
    // required up front.
  }

  async function healthcheck(): Promise<{ ok: boolean; latencyMs: number; message?: string }> {
    const started = Date.now();
    if (mode === "mock") {
      return { ok: true, latencyMs: Date.now() - started, message: "mock mode" };
    }
    try {
      guard("healthcheck");
      // Probe the pre-alpha endpoint. A real healthcheck would hit a
      // dedicated /health route; we GET the docs index as a liveness probe.
      const res = await fetch(`${endpointUrl}/docs`, { method: "GET" }).catch(() => null);
      return {
        ok: res ? res.status < 500 : false,
        latencyMs: Date.now() - started,
        message: res ? `http ${res.status} (pre-alpha)` : "endpoint unreachable",
      };
    } catch (err) {
      return {
        ok: false,
        latencyMs: Date.now() - started,
        message: err instanceof Error ? err.message : "unknown error",
      };
    }
  }

  // Mock mode short-circuit — same shape as live mode would produce but
  // generated deterministically per invoice. Mock mode is the default
  // demo path because Ika's live mode is itself "mock signer pre-alpha"
  // and gives us nothing more for hackathon submission purposes.
  if (mode === "mock") {
    return {
      mode,
      network,
      featureFlag: enabled,
      initialise,
      healthcheck,
      supportedChains: () => SUPPORTED_CHAINS,
      createDWallet: async ({ chain, invoiceId }) => ({
        dwalletId: `dwallet_mock_${invoiceId.slice(0, 8)}_${chain}`,
        chain,
        receiveAddress: mockReceiveAddress(chain, invoiceId),
        publicKey: `mock_pk_${Math.random().toString(36).slice(2, 22)}`,
        status: "pending_dkg",
        createdAt: new Date().toISOString(),
      }),
      transferAuthority: async ({ dwalletId, programPdaAddress }) => {
        void dwalletId;
        void programPdaAddress;
        return {
          ok: true,
          signature: `mock_sig_${Math.random().toString(36).slice(2, 14)}${Math.random().toString(36).slice(2, 14)}`,
        };
      },
      approveMessage: async ({ dwalletId, message, reason }) => {
        void message;
        void reason;
        return {
          signatureId: `sig_${dwalletId.slice(-8)}_${Math.random().toString(36).slice(2, 8)}`,
          signature: `mock_sig_${Math.random().toString(36).slice(2, 60)}`,
          messageApprovalAccount: `MockMA${Math.random().toString(36).slice(2, 30)}`,
          mockSigner: true,
          signedAt: new Date().toISOString(),
        };
      },
      readMessageApproval: async ({ messageApprovalAccount }) => ({
        signature: `mock_sig_read_${messageApprovalAccount.slice(-8)}`,
        readyForBroadcast: true,
      }),
    };
  }

  // ─── Live mode (pre-alpha mock signer) ───────────────────────────────
  //
  // We dynamic-import @ika.xyz/sdk so callers in mock mode (the bulk of
  // current usage) don't pay the bundle-size cost. The pre-alpha SDK
  // exports are documented at docs.ika.xyz/docs/sdk; the Solana program
  // ID and gRPC endpoint are consumed transparently.
  //
  // Note: as of 2026-04-30 Ika has not published exhaustive type
  // signatures for every export, so we consume the SDK behind a typed
  // facade to keep our wrapper's surface stable when their API shifts
  // between pre-alpha minor versions.

  async function loadSdk() {
    return await import("@ika.xyz/sdk").catch(() => {
      throw new Error(
        "[@dodorail/ika] @ika.xyz/sdk not installed. Run `pnpm add @ika.xyz/sdk` in packages/integrations/ika to use live mode.",
      );
    });
  }

  return {
    mode,
    network,
    featureFlag: enabled,
    initialise,
    healthcheck,
    supportedChains: () => SUPPORTED_CHAINS,
    async createDWallet({ chain, invoiceId }) {
      guard("createDWallet");
      const sdk = await loadSdk();
      // The Ika SDK's pre-alpha API uses a function-factory pattern similar
      // to Umbra's; the exact method name is documented as `createDWallet`
      // in their getting-started page. We bridge into our typed shape.
      type CreateFn = (args: {
        chain: IkaSupportedChain;
        invoiceMetadata?: string;
      }) => Promise<{
        dwalletId: string;
        receiveAddress: string;
        publicKey: string;
      }>;
      const createDWalletFn = (sdk as unknown as { createDWallet?: CreateFn }).createDWallet;
      if (!createDWalletFn) {
        throw new Error(
          "[@dodorail/ika] live mode: @ika.xyz/sdk does not expose createDWallet. Pre-alpha API may have shifted — check docs.ika.xyz/docs/sdk and update the wrapper.",
        );
      }
      const result = await createDWalletFn({
        chain,
        invoiceMetadata: invoiceId,
      });
      return {
        dwalletId: result.dwalletId,
        chain,
        receiveAddress: result.receiveAddress,
        publicKey: result.publicKey,
        status: "pending_dkg",
        createdAt: new Date().toISOString(),
      };
    },
    async transferAuthority(input) {
      guard("transferAuthority");
      const sdk = await loadSdk();
      type TransferFn = (args: {
        dwalletId: string;
        programPdaAddress: string;
      }) => Promise<{ signature: string }>;
      const fn = (sdk as unknown as { transferAuthority?: TransferFn }).transferAuthority;
      if (!fn) {
        throw new Error(
          "[@dodorail/ika] live mode: transferAuthority not exposed. Update wrapper to match current pre-alpha API.",
        );
      }
      const result = await fn(input);
      return { ok: true, signature: result.signature };
    },
    async approveMessage(input) {
      guard("approveMessage");
      const sdk = await loadSdk();
      type ApproveFn = (args: {
        dwalletId: string;
        message: Uint8Array;
        reason: string;
      }) => Promise<{
        signatureId: string;
        signature: string;
        messageApprovalAccount: string;
      }>;
      const fn = (sdk as unknown as { approveMessage?: ApproveFn }).approveMessage;
      if (!fn) {
        throw new Error(
          "[@dodorail/ika] live mode: approveMessage not exposed. Update wrapper to match current pre-alpha API.",
        );
      }
      const result = await fn(input);
      return {
        signatureId: result.signatureId,
        signature: result.signature,
        messageApprovalAccount: result.messageApprovalAccount,
        mockSigner: true, // ALWAYS true on pre-alpha — flips to false post-Alpha-1
        signedAt: new Date().toISOString(),
      };
    },
    async readMessageApproval(input) {
      guard("readMessageApproval");
      const sdk = await loadSdk();
      type ReadFn = (args: { messageApprovalAccount: string }) => Promise<{
        signature: string;
        readyForBroadcast: boolean;
      }>;
      const fn = (sdk as unknown as { readMessageApproval?: ReadFn }).readMessageApproval;
      if (!fn) {
        throw new Error(
          "[@dodorail/ika] live mode: readMessageApproval not exposed.",
        );
      }
      return await fn(input);
    },
  };
}

export const IKA_CONSTANTS = {
  DEFAULT_PRE_ALPHA_ENDPOINT,
  SUPPORTED_CHAINS,
} as const;

// Type re-export for downstream pay-page consumers.
export type { PublicKey };
